// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB58WK9lj3Y06KKq-0fEu-WVtnkcsk-KbA',
    appId: '1:97108639991:web:b33a18a8d68c15572f53f2',
    messagingSenderId: '97108639991',
    projectId: 'job-interview-46c64',
    authDomain: 'job-interview-46c64.firebaseapp.com',
    storageBucket: 'job-interview-46c64.firebasestorage.app',
    measurementId: 'G-P32GX0SPH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFnaSCwgM3D_lUOLdrxu09v2B5lTqBhMQ',
    appId: '1:97108639991:android:7657be9535cc4d6b2f53f2',
    messagingSenderId: '97108639991',
    projectId: 'job-interview-46c64',
    storageBucket: 'job-interview-46c64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClGHrEUdPKJN6uSg0Ds5Buib0eI1Hh3C4',
    appId: '1:97108639991:ios:80416ba448f8df1e2f53f2',
    messagingSenderId: '97108639991',
    projectId: 'job-interview-46c64',
    storageBucket: 'job-interview-46c64.firebasestorage.app',
    androidClientId: '97108639991-lsfa15i040a7nohujmtfe9mbnssdaqc5.apps.googleusercontent.com',
    iosClientId: '97108639991-a4mddp74h5cmcj5u4gevisfa92ufidoj.apps.googleusercontent.com',
    iosBundleId: 'com.example.myWebApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClGHrEUdPKJN6uSg0Ds5Buib0eI1Hh3C4',
    appId: '1:97108639991:ios:80416ba448f8df1e2f53f2',
    messagingSenderId: '97108639991',
    projectId: 'job-interview-46c64',
    storageBucket: 'job-interview-46c64.firebasestorage.app',
    androidClientId: '97108639991-lsfa15i040a7nohujmtfe9mbnssdaqc5.apps.googleusercontent.com',
    iosClientId: '97108639991-a4mddp74h5cmcj5u4gevisfa92ufidoj.apps.googleusercontent.com',
    iosBundleId: 'com.example.myWebApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB58WK9lj3Y06KKq-0fEu-WVtnkcsk-KbA',
    appId: '1:97108639991:web:4c62879d7434bc2e2f53f2',
    messagingSenderId: '97108639991',
    projectId: 'job-interview-46c64',
    authDomain: 'job-interview-46c64.firebaseapp.com',
    storageBucket: 'job-interview-46c64.firebasestorage.app',
    measurementId: 'G-HHMW1JSQLY',
  );
}
